#!/bin/bash

# Just a wrapper script to launch rofi

# Set accent colours
if [[ $1 = "--red" ]]; then
    ACCENT='#d12f2c'
elif [[ $1 = "--green" ]]; then
    ACCENT='#819400'
elif [[ $1 = "--yellow" ]]; then
    ACCENT='#b08500'
elif [[ $1 = "--blue" ]]; then
    ACCENT='#2587cc'
elif [[ $1 = "--magenta" ]]; then
    ACCENT='#696ebf'
elif [[ $1 = "--cyan" ]]; then
    ACCENT='#289c93'
else
    ACCENT='#d12f2c'
fi

rofi -show drun -sidebar-mode \
-modi run,drun,window \
-hide-scrollbar true \
-bw 2 \
-lines 12 \
-padding 24 \
-width 60 \
-location 0 \
-columns 3 \
-font "cinnamonroll 10" \
-color-enabled true \
-color-window "#141c21,#141c21,#141c21" \
-color-normal "#141c21,#93a1a1,#141c21,#141c21,$ACCENT" \
-color-active "#141c21,#696ebf,#141c21,#141c21,$ACCENT" \
-color-urgent "#141c21,#b08500,#141c21,#141c21,$ACCENT"
