#!/bin/dash

# Change TTY colors
# Run this script from TTY
echo -en "\e]P0141c21" #black
echo -en "\e]P8263640" #darkgrey
echo -en "\e]P1d12f2c" #darkred
echo -en "\e]P9fa3935" #red
echo -en "\e]P2819400" #darkgreen
echo -en "\e]PAa4bd00" #green
echo -en "\e]P3b08500" #brown
echo -en "\e]PBd9a400" #yellow
echo -en "\e]P42587cc" #darkblue
echo -en "\e]PC2ca2f5" #blue
echo -en "\e]P5696ebf" #darkmagenta
echo -en "\e]PD8086e8" #magenta
echo -en "\e]P6289c93" #darkcyan
echo -en "\e]PE33c5ba" #cyan
echo -en "\e]P7bfbaac" #lightgrey
echo -en "\e]PFfdf6e3" #white
clear
