#!/bin/bash

# Download mp3 from youtube, ssst this is illegal actually
# Need youtube-dl package
# I tested this on Void works without problem
# But on Debian doesn't work, youtube-dl version too old :(
# Usage 'ytmp3 <video url>'
# For example 'ytmp3 https://www.youtube.com/watch?v=Tq8u0uDK61E'
# If no error reported it would stored in home
# Cheers! Addy

youtube-dl $1\
	--add-metadata --metadata-from-title "%(artist)s - %(title)s" \
	--extract-audio --audio-format mp3 --audio-quality 0 --prefer-ffmpeg \
	--youtube-skip-dash-manifest --ignore-errors --restrict-filenames \
	--verbose $f
notify-send "Youtube" "Something Happen"
