#!/bin/dash

# Environtment
export PATH="${PATH}:$HOME/.scripts"
export RANGER_LOAD_DEFAULT_RC=FALSE
export EDITOR=vim

# Autostart Apps
xset +fp ~/.fonts/misc/
xset b off
xset r rate 250 25
xbacklight -set 5
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
pcmanfm -d &
compton -b
hsetroot -center ~/.wallpaper.jpg
xsettingsd &
dunst &

# Touchpad settings
synclient \
VertEdgeScroll=0 HorizEdgeScroll=0 \
VertTwoFingerScroll=1 HorizTwoFingerScroll=1 \
VertScrollDelta=320 HorizScrollDelta=320 \
MinSpeed=0.05 MaxSpeed=1.2 \
AccelFactor=0.04 CoastingSpeed=10 \
TapButton1=0 TapButton2=0 TapButton3=0

# System Tray
trayer \
--align right --widthtype request --heighttype pixel --height 28 \
--transparent true --alpha 255 &

# Panel
[ -e "/tmp/panel-fifo" ] && rm "/tmp/panel-fifo"
mkfifo "/tmp/panel-fifo"
i3status > "/tmp/panel-fifo" &
statusline() {
while read -r line ; do
    case $line in
        A*) wifi="%{B#d12f2c}%{F#263640} %{A:wicd-gtk --no-tray &:}${line#?}%{A} %{B-}%{F-}";;
        B*) battery="%{B#819400}%{F#263640} ${line#?} %{B-}%{F-}";;
        C*) volume="%{B#b08500}%{F#263640} %{A4:pulsevol --up:}%{A5:pulsevol --down:}\
%{A:pavucontrol &:}${line#?}%{A}%{A}%{A} %{B-}%{F-}";;
        D*) temp="%{B#2587cc}%{F#263640} ${line#?} %{B-}%{F-}";;
        E*) load="%{B#696ebf}%{F#263640} %{A:x-terminal-emulator \
-hold -e htop &:}${line#?}%{A} %{B-}%{F-}";;
        F*) disk="%{B#289c93}%{F#263640} %{A:pcmanfm &:}${line#?}%{A} %{B-}%{F-}";;
        G*) clock="%{B#263640}%{F#93a1a1} ${line#?} %{B-}%{F-}";;
    esac
    printf "%s\n" "%{l}${wifi}${battery}${volume}${temp}${load}${disk}%{r}${clock}"
done
}
statusline < "/tmp/panel-fifo" | lemonbar -g x28 \
-f -*-rissole-* -f -*-waffle-* -B "#141c21" -F "#93a1a1" | dash &
